# Generated by Django 5.1.5 on 2025-01-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_auth', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
